export type RuntimeConfig = {
  NEXT_PUBLIC_ENCRYPT_ASSET?: string
  NEXT_PUBLIC_METADATACACHE_URI?: string
  NEXT_PUBLIC_SSI_WALLET_API?: string
  NEXT_PUBLIC_SSI_DEFAULT_POLICIES_URL?: string
  NEXT_PUBLIC_SSI_POLICY_SERVER?: string
  NEXT_PUBLIC_SSI_ENABLED?: string
  NEXT_PUBLIC_PROVIDER_URL?: string
  NEXT_PUBLIC_IPFS_UNPIN_FILES?: string
  NEXT_PUBLIC_NODE_URI?: string
  NEXT_PUBLIC_IPFS_GATEWAY?: string
  NEXT_PUBLIC_IPFS_JWT?: string
  NEXT_PUBLIC_OPA_SERVER_URL?: string
  NEXT_PUBLIC_SHOW_ONBOARDING_MODULE_BY_DEFAULT?: string
  NEXT_PUBLIC_NODE_URI_INDEXED?: string
  NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID?: string
  NEXT_PUBLIC_INFURA_PROJECT_ID?: string
  NEXT_PUBLIC_CONSUME_MARKET_FEE?: string
  NEXT_PUBLIC_CONSUME_MARKET_ORDER_FEE?: string
  NEXT_PUBLIC_FIXED_RATE_EXCHANGE_ADDRESS?: string
  NEXT_PUBLIC_DISPENSER_ADDRESS?: string
  NEXT_PUBLIC_NFT_FACTORY_ADDRESS?: string
  NEXT_PUBLIC_ROUTER_FACTORY_ADDRESS?: string
  NEXT_PUBLIC_ACCESS_LIST_FACTORY_ADDRESS?: string
  NEXT_PUBLIC_NODE_URI_MAP?: string
  NEXT_PUBLIC_ERC20_ADDRESSES?: string
  NEXT_PUBLIC_CREDENTIAL_VALIDITY_DURATION?: string
  NEXT_PUBLIC_MARKET_FEE_ADDRESS?: string
  NEXT_PUBLIC_MARKET_DEVELOPMENT?: string
}

declare global {
  interface Window {
    __RUNTIME_CONFIG__?: RuntimeConfig
  }
}

const runtimeConfig: RuntimeConfig = (() => {
  const baseConfig: RuntimeConfig = {
    NEXT_PUBLIC_ENCRYPT_ASSET: process.env.NEXT_PUBLIC_ENCRYPT_ASSET,
    NEXT_PUBLIC_METADATACACHE_URI: process.env.NEXT_PUBLIC_METADATACACHE_URI,
    NEXT_PUBLIC_SSI_WALLET_API: process.env.NEXT_PUBLIC_SSI_WALLET_API,
    NEXT_PUBLIC_SSI_DEFAULT_POLICIES_URL:
      process.env.NEXT_PUBLIC_SSI_DEFAULT_POLICIES_URL,
    NEXT_PUBLIC_SSI_POLICY_SERVER: process.env.NEXT_PUBLIC_SSI_POLICY_SERVER,
    NEXT_PUBLIC_SSI_ENABLED: process.env.NEXT_PUBLIC_SSI_ENABLED,
    NEXT_PUBLIC_PROVIDER_URL: process.env.NEXT_PUBLIC_PROVIDER_URL,
    NEXT_PUBLIC_IPFS_UNPIN_FILES: process.env.NEXT_PUBLIC_IPFS_UNPIN_FILES,
    NEXT_PUBLIC_NODE_URI: process.env.NEXT_PUBLIC_NODE_URI,
    NEXT_PUBLIC_IPFS_GATEWAY: process.env.NEXT_PUBLIC_IPFS_GATEWAY,
    NEXT_PUBLIC_IPFS_JWT: process.env.NEXT_PUBLIC_IPFS_JWT,
    NEXT_PUBLIC_OPA_SERVER_URL: process.env.NEXT_PUBLIC_OPA_SERVER_URL,
    NEXT_PUBLIC_SHOW_ONBOARDING_MODULE_BY_DEFAULT:
      process.env.NEXT_PUBLIC_SHOW_ONBOARDING_MODULE_BY_DEFAULT,
    NEXT_PUBLIC_NODE_URI_INDEXED: process.env.NEXT_PUBLIC_NODE_URI_INDEXED,
    NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID:
      process.env.NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID,
    NEXT_PUBLIC_INFURA_PROJECT_ID: process.env.NEXT_PUBLIC_INFURA_PROJECT_ID,
    NEXT_PUBLIC_CONSUME_MARKET_FEE: process.env.NEXT_PUBLIC_CONSUME_MARKET_FEE,
    NEXT_PUBLIC_CONSUME_MARKET_ORDER_FEE:
      process.env.NEXT_PUBLIC_CONSUME_MARKET_ORDER_FEE,
    NEXT_PUBLIC_FIXED_RATE_EXCHANGE_ADDRESS:
      process.env.NEXT_PUBLIC_FIXED_RATE_EXCHANGE_ADDRESS,
    NEXT_PUBLIC_DISPENSER_ADDRESS: process.env.NEXT_PUBLIC_DISPENSER_ADDRESS,
    NEXT_PUBLIC_NFT_FACTORY_ADDRESS:
      process.env.NEXT_PUBLIC_NFT_FACTORY_ADDRESS,
    NEXT_PUBLIC_ROUTER_FACTORY_ADDRESS:
      process.env.NEXT_PUBLIC_ROUTER_FACTORY_ADDRESS,
    NEXT_PUBLIC_ACCESS_LIST_FACTORY_ADDRESS:
      process.env.NEXT_PUBLIC_ACCESS_LIST_FACTORY_ADDRESS,
    NEXT_PUBLIC_NODE_URI_MAP: process.env.NEXT_PUBLIC_NODE_URI_MAP,
    NEXT_PUBLIC_ERC20_ADDRESSES: process.env.NEXT_PUBLIC_ERC20_ADDRESSES,
    NEXT_PUBLIC_CREDENTIAL_VALIDITY_DURATION:
      process.env.NEXT_PUBLIC_CREDENTIAL_VALIDITY_DURATION,
    NEXT_PUBLIC_MARKET_FEE_ADDRESS: process.env.NEXT_PUBLIC_MARKET_FEE_ADDRESS,
    NEXT_PUBLIC_MARKET_DEVELOPMENT: process.env.NEXT_PUBLIC_MARKET_DEVELOPMENT
  }

  if (typeof window !== 'undefined' && window.__RUNTIME_CONFIG__) {
    return { ...baseConfig, ...window.__RUNTIME_CONFIG__ }
  }

  return baseConfig
})()

export function getRuntimeConfig(): RuntimeConfig {
  return runtimeConfig
}
