export type RuntimeConfig = {
  NEXT_PUBLIC_SSI_WALLET_API?: string
  NEXT_PUBLIC_PROVIDER_URL?: string
  NEXT_PUBLIC_FIXED_RATE_EXCHANGE_ADDRESS?: string
  NEXT_PUBLIC_DISPENSER_ADDRESS?: string
  NEXT_PUBLIC_NFT_FACTORY_ADDRESS?: string
  NEXT_PUBLIC_ROUTER_FACTORY_ADDRESS?: string
  NEXT_PUBLIC_ACCESS_LIST_FACTORY_ADDRESS?: string
  NEXT_PUBLIC_NODE_URI_MAP?: string
  NEXT_PUBLIC_ERC20_ADDRESSES?: string
  NEXT_PUBLIC_INFURA_PROJECT_ID?: string
  NEXT_PUBLIC_MARKET_DEVELOPMENT?: string
  NEXT_PUBLIC_CREDENTIAL_VALIDITY_DURATION?: string
}

declare global {
  interface Window {
    __RUNTIME_CONFIG__?: RuntimeConfig
  }
}

const runtimeConfig: RuntimeConfig = (() => {
  const baseConfig: RuntimeConfig = {
    NEXT_PUBLIC_SSI_WALLET_API: process.env.NEXT_PUBLIC_SSI_WALLET_API,
    NEXT_PUBLIC_PROVIDER_URL: process.env.NEXT_PUBLIC_PROVIDER_URL,
    NEXT_PUBLIC_FIXED_RATE_EXCHANGE_ADDRESS:
      process.env.NEXT_PUBLIC_FIXED_RATE_EXCHANGE_ADDRESS,
    NEXT_PUBLIC_DISPENSER_ADDRESS: process.env.NEXT_PUBLIC_DISPENSER_ADDRESS,
    NEXT_PUBLIC_NFT_FACTORY_ADDRESS:
      process.env.NEXT_PUBLIC_NFT_FACTORY_ADDRESS,
    NEXT_PUBLIC_ROUTER_FACTORY_ADDRESS:
      process.env.NEXT_PUBLIC_ROUTER_FACTORY_ADDRESS,
    NEXT_PUBLIC_ACCESS_LIST_FACTORY_ADDRESS:
      process.env.NEXT_PUBLIC_ACCESS_LIST_FACTORY_ADDRESS,
    NEXT_PUBLIC_NODE_URI_MAP: process.env.NEXT_PUBLIC_NODE_URI_MAP,
    NEXT_PUBLIC_ERC20_ADDRESSES: process.env.NEXT_PUBLIC_ERC20_ADDRESSES,
    NEXT_PUBLIC_INFURA_PROJECT_ID: process.env.NEXT_PUBLIC_INFURA_PROJECT_ID,
    NEXT_PUBLIC_MARKET_DEVELOPMENT: process.env.NEXT_PUBLIC_MARKET_DEVELOPMENT,
    NEXT_PUBLIC_CREDENTIAL_VALIDITY_DURATION:
      process.env.NEXT_PUBLIC_CREDENTIAL_VALIDITY_DURATION
  }

  if (typeof window !== 'undefined' && window.__RUNTIME_CONFIG__) {
    return { ...baseConfig, ...window.__RUNTIME_CONFIG__ }
  }

  return baseConfig
})()

export function getRuntimeConfig(): RuntimeConfig {
  return runtimeConfig
}
